all:
	gcc project2_chat.c -o chat
	gcc project2_receiver_4k.c -o receive_4k
	gcc project2_receiver_2m.c -o receive_2m
	gcc project2_receiver_1g.c -o receive_1g
clean:
	rm chat
	rm receive_4k
	rm receive_2m
	rm receive_1g
